image: node

stages:
   - build
   - test
   - deploy
   - deploy staging
   - deployment tests

cache:
  key: ${CI_ENVIRONMENT_SLUG}
  paths:
    - node_modules/



build website:

  stage: build 
 
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
    
  artifacts:
    paths:
    - ./public

test artifact:

  stage: test
 
  

  script:
    - grep -q "Gatsby" ./public/index.html
    


test website:
   
  stage: test

  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"


deploy staging:
  stage: deploy staging
  environment:
    name: staging
    url: http://noonno-staging.surge.sh
  when: manual
  script:
    - npm install --g surge
    - surge --project ./public --domain noonno-staging.surge.sh
  

deploy to surge:
  stage: deploy
  environment:
    name: productoin
    url: http://noonno.surge.sh
  script:
    - npm install --g surge
    - surge --project ./public --domain noonno.surge.sh

test deployment:
  stage: deployment tests
  

  script:
    - apt-get update; apt-get install curl
    - curl -s "https://noonno.surge.sh" | grep -q "Hi people"
    - curl -s "https://noonno.surge.sh" | grep -q "$CI_COMMIT_SHORT_SHA"  
      
